language: node_js

node_js:
  - stable
  - "7"
  - "6"
  - "5"

install:
  - npm install

script:
  - npm run cover

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"